In [1]:
import numpy as np
np.set_printoptions(precision=1)

In [2]:
# example = np.array(
#     [[0      ,      3,      8,  np.inf,     -4],
#     [np.inf ,      0, np.inf,       1,      7],
#     [np.inf ,      4,      0,  np.inf, np.inf],
#     [     2 , np.inf,     -5,       0, np.inf],
#     [ np.inf, np.inf, np.inf,       6,      0]]
#     )

#example from https://www.gatevidyalay.com/floyd-warshall-algorithm-shortest-path-algorithm/
example = np.array([
    [0, 8, np.inf, 1],
    [np.inf, 0, 1, np.inf],
    [4, np.inf, 0, np.inf],
    [np.inf, 2, 9, 0]
])

In [3]:
example

array([[ 0.,  8., inf,  1.],
       [inf,  0.,  1., inf],
       [ 4., inf,  0., inf],
       [inf,  2.,  9.,  0.]])

In [4]:
def FloydWarshall(W) :
    n = W.shape[0]
    print("Size : "+str(n))
    D = [None] * (n+1)
    D[-1] = W
    print("Input : \n", D[-1])
    for (k) in range(0, n):
        D[k] = np.empty([n,n])
        for (i) in range (0, n):
            for (j) in range (0, n):
                #print(i, j, k)
                D[k][i, j] = min(D[k-1][i, j], D[k-1][i, k]+ D[k-1][k, j])
        print("\nIteration-" + str(k))
        print(D[k])
        
    return D[n-1]

In [5]:
FloydWarshall(example)

Size : 4
Input : 
 [[ 0.  8. inf  1.]
 [inf  0.  1. inf]
 [ 4. inf  0. inf]
 [inf  2.  9.  0.]]

Iteration-0
[[ 0.  8. inf  1.]
 [inf  0.  1. inf]
 [ 4. 12.  0.  5.]
 [inf  2.  9.  0.]]

Iteration-1
[[ 0.  8.  9.  1.]
 [inf  0.  1. inf]
 [ 4. 12.  0.  5.]
 [inf  2.  3.  0.]]

Iteration-2
[[ 0.  8.  9.  1.]
 [ 5.  0.  1.  6.]
 [ 4. 12.  0.  5.]
 [ 7.  2.  3.  0.]]

Iteration-3
[[0. 3. 4. 1.]
 [5. 0. 1. 6.]
 [4. 7. 0. 5.]
 [7. 2. 3. 0.]]


array([[0., 3., 4., 1.],
       [5., 0., 1., 6.],
       [4., 7., 0., 5.],
       [7., 2., 3., 0.]])