In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(precision=3)

In [2]:
# Input Array
# AX=B
A = np.array(
    [[5, 1, -1],
    [10, 1, -8],
    [-5, -4, 0]],
    np.float32
)

B = np.array(
    [2, -7, -1]
)



## LU Decomposition# 
# 1. Decomposition
Let

$\begin{align} AX=B, \thinspace where \thinspace A=LU\end{align}$


$$\begin{bmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{bmatrix}=\begin{bmatrix}l_{11}&0&0\\l_{21}&l_{22}&0\\l_{31}&l_{32}&l_{33}\end{bmatrix}\begin{bmatrix}u_{11}&u_{12}&u_{13}\\0&u_{22}&u_{23}\\0&0&u_{33}\end{bmatrix}$$

moreinfo : 
https://rosettacode.org/wiki/LU_decomposition

In [3]:
def LU_decomposition(A):
  """Perform LU decomposition using the Doolittle factorisation."""

  L = np.zeros_like(A)
  U = np.zeros_like(A)
  N = np.size(A, 0)

  for k in range(N):
    L[k, k] = 1
    print("a", k, k, " : ", A[k, k])
    print("Sum", k, k, " : ", np.dot(L[k, :k], U[:k, k]))
    U[k, k] = (A[k, k] - np.dot(L[k, :k], U[:k, k])) / L[k, k]
    print("u", k, k, " : ", U[k, k])
    print("----------")
    for j in range(k+1, N):
      print("a", k, j, " : ", A[k, j])
      print("Sum", k, j, " : ", np.dot(L[k, :k], U[:k, j]))
      U[k, j] = (A[k, j] - np.dot(L[k, :k], U[:k, j])) / L[k, k]
      print("u", k, j, " : ", U[k, j])
      print("----------")

    for i in range(k+1, N):
      print("a", i, k, " : ", A[i, k])
      print("Sum", i, k, " : ", np.dot(L[i, :k], U[:k, k]))
      print("U", k, k, " : ", U[k, k])
      
      L[i, k] = (A[i, k] - np.dot(L[i, :k], U[:k, k])) / U[k, k]
      print("l", i, k, " : ", L[i, k])
      print("----------")

  print("Lower:\n",L)
  print("Upper:\n",U)

  return L, U

# Solve
## LUX=B
LY=B

UX = Y

In [4]:
L, U = LU_decomposition(A)
print("A : L.U\n",np.dot(L, U))
print("A : \n",A)


a 0 0  :  5.0
Sum 0 0  :  0.0
u 0 0  :  5.0
----------
a 0 1  :  1.0
Sum 0 1  :  0.0
u 0 1  :  1.0
----------
a 0 2  :  -1.0
Sum 0 2  :  0.0
u 0 2  :  -1.0
----------
a 1 0  :  10.0
Sum 1 0  :  0.0
U 0 0  :  5.0
l 1 0  :  2.0
----------
a 2 0  :  -5.0
Sum 2 0  :  0.0
U 0 0  :  5.0
l 2 0  :  -1.0
----------
a 1 1  :  1.0
Sum 1 1  :  2.0
u 1 1  :  -1.0
----------
a 1 2  :  -8.0
Sum 1 2  :  -2.0
u 1 2  :  -6.0
----------
a 2 1  :  -4.0
Sum 2 1  :  -1.0
U 1 1  :  -1.0
l 2 1  :  3.0
----------
a 2 2  :  0.0
Sum 2 2  :  -17.0
u 2 2  :  17.0
----------
Lower:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  3.  1.]]
Upper:
 [[ 5.  1. -1.]
 [ 0. -1. -6.]
 [ 0.  0. 17.]]
A : L.U
 [[ 5.  1. -1.]
 [10.  1. -8.]
 [-5. -4.  0.]]
A : 
 [[ 5.  1. -1.]
 [10.  1. -8.]
 [-5. -4.  0.]]


In [5]:
Y = np.linalg.solve(L, B)
print("Y : \n", Y)

X = np.linalg.solve(U, Y)
print("X : \n", X)


Y : 
 [  2. -11.  34.]
X : 
 [ 1. -1.  2.]
